export const spacesData = [
  {
    id: 1,
    categories: ["Fruit Pulps", "Concentrates"],
    image: "/spaces/space-1.jpg",
    date: "Available Year-Round",
    name: "Mango Pulp (Alphonso & Totapuri)",
    location: "Aseptic / Frozen",
    clientImage: "/spaces/client-1.jpeg",
    clientName: "Varun Agro",
    route: "/sample-space",
  },
  {
    id: 2,
    categories: ["Fruit Pulps", "Concentrates"],
    image: "/spaces/space-2.jpg",
    date: "Available Year-Round",
    name: "Guava Pulp (White & Pink)",
    location: "Aseptic / Frozen",
    clientImage: "/spaces/client-2.jpeg",
    clientName: "Varun Agro",
    route: "/sample-space",
  },
  {
    id: 3,
    categories: ["Vegetables", "Paste"],
    image: "/spaces/space-3.jpg",
    date: "Available Year-Round",
    name: "Tomato Paste & Puree",
    location: "Aseptic / Canned",
    clientImage: "/spaces/client-3.jpeg",
    clientName: "Varun Agro",
    route: "/sample-space",
  },
  {
    id: 4,
    categories: ["Frozen", "Vegetables"],
    image: "/spaces/space-4.jpg",
    date: "Seasonal",
    name: "IQF Green Peas",
    location: "Frozen",
    clientImage: "/spaces/client-4.jpeg",
    clientName: "Varun Agro",
    route: "/sample-space",
  },
  {
    id: 5,
    categories: ["Frozen", "Fruits"],
    image: "/spaces/space-5.jpg",
    date: "Seasonal",
    name: "IQF Strawberry",
    location: "Frozen",
    clientImage: "/spaces/client-5.jpeg",
    clientName: "Varun Agro",
    route: "/sample-space",
  },
  {
    id: 6,
    categories: ["Sauces", "Condiments"],
    image: "/spaces/space-6.jpg",
    date: "Available Year-Round",
    name: "Tomato Ketchup & Sauces",
    location: "Retail / Bulk",
    clientImage: "/spaces/client-6.jpeg",
    clientName: "Varun Agro",
    route: "/sample-space",
  },
  {
    id: 7,
    categories: ["Fruit Pulps", "Concentrates"],
    image: "/spaces/space-7.jpg",
    date: "Available Year-Round",
    name: "Papaya Pulp",
    location: "Aseptic / Frozen",
    clientImage: "/spaces/client-7.jpeg",
    clientName: "Varun Agro",
    route: "/sample-space",
  },
];
